# Generated by Django 2.2.5 on 2020-06-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blogs_reads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='reads',
        ),
        migrations.AddField(
            model_name='blogs',
            name='postuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
